# Kafka
bootstrap.servers=kafka:29092
group.id=update-document-group
topic=document_watermark_processed

# Database
db.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/document_db?user=${DB_USERNAME}&password=${DB_PASSWORD}&sslmode=${DB_SSL_MODE}
db.user=${DB_USERNAME}
db.password=${DB_PASSWORD}