# Kafka
bootstrap.servers=kafka:29092
group.id=update-document-group
topic=document_watermark_processed

# Database
db.url=jdbc:postgresql://host.docker.internal:5432/document_db?user=postgres&password=1234&sslmode=disable
db.user=postgres
db.password=1234
