rootProject.name = 'system-microservice-share-documents'

//Service
include 'EurekaService'
include 'APIGatewayService'
include 'UserService'
include 'DocumentService'
include 'AuthAccessControlService'
include 'AuditLogService'
include 'CloudConfigServerService'
include 'WatermarkWorkerService'
include 'AppCommonService'
//Job Flink
include 'UpdateDocumentData'
include 'CDCUpdateDocumentDataCache'
include 'CDCUpdateUserDataCache'
include 'EncryptDocumentKeysForNewMember'
include 'MalwareScanWorkerService'
