# Job
job.name=cdc-update-user-data-cache
flink.parallelism=2
flink.checkpoint.interval.ms=60000

# Kafka
kafka.bootstrap.servers=kafka:29092
kafka.topic=cdc-update-user-cache
kafka.group.id=cdc-user-group

# Redis
#redis.host=redis-13180.c92.us-east-1-3.ec2.cloud.redislabs.com
#redis.port=13180
#redis.username=default
#redis.password=isE0Im1PteG3ka8bMnj4hiGFqpV8SlqL
#redis.pool.maxTotal=8
#redis.pool.maxIdle=8
# Redis - try 'redis' hostname first (if Redis is in same Docker network)
# If Redis is on host machine, use host gateway IP or 172.17.0.1
redis.host=redis
redis.port=6379
redis.username=default
redis.password=
redis.pool.maxTotal=8
redis.pool.maxIdle=8

# Elasticsearch
elasticsearch.host=elasticsearch
elasticsearch.port=9200
elasticsearch.scheme=http
