# Job
job.name=cdc-update-user-data-cache
flink.parallelism=2
flink.checkpoint.interval.ms=60000

# Kafka
kafka.bootstrap.servers=kafka:29092
kafka.topic=cdc-update-user-cache
kafka.group.id=cdc-user-group

# Redis
redis.host=redis
redis.port=6379
redis.username=default
redis.password=
redis.pool.maxTotal=8
redis.pool.maxIdle=8

# Elasticsearch
elasticsearch.host=elasticsearch
elasticsearch.port=9200
elasticsearch.scheme=http

# Keycloak
keycloak.server-url=http://host.docker.internal:9090
keycloak.admin-realm=master
keycloak.admin-username=admin
keycloak.admin-password=admin
keycloak.client-id=admin-cli
keycloak.realm=system-share-docs
