bootstrap.servers=kafka:29092
group.id=encrypt-document-keys-for-new-member
topic=member_joined_group

db.url=jdbc:postgresql://localhost:5432/document_db
db.user=postgres
db.password=1234

user.service.url=http://localhost:8081

vault.url=http://localhost:8200
vault.token=hvs.CAESIFqotF86IUb-Nuf5GOmGsDethx2FxsEgHpRuWU7hJOLRGh4KHGh2cy5ZZUtrbkZGeFJoZFFDNGFGeXJYSGxVdjE
vault.transit.key.name=colendungbocuoc5382

batch.size=10
parallelism=4


















