bootstrap.servers=kafka:29092
group.id=encrypt-document-keys-for-new-member
topic=member_joined_group

# Database
db.url=jdbc:postgresql://host.docker.internal:5432/document_db?user=postgres&password=1234&sslmode=disable
db.user=postgres
db.password=1234

user.service.url=http://host.docker.internal:8080

vault.url=http://host.docker.internal:8200
vault.token=hvs.CAESIFqotF86IUb-Nuf5GOmGsDethx2FxsEgHpRuWU7hJOLRGh4KHGh2cy5ZZUtrbkZGeFJoZFFDNGFGeXJYSGxVdjE
vault.transit.key.name=colendungbocuoc5382

batch.size=10
parallelism=4

keycloak.url=http://host.docker.internal:9090
keycloak.realm=system-share-docs
keycloak.client.id=token-service
keycloak.client.secret=jgSEuPDTE9k8oQJme2dKaNWLAPHRSi9L