server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false

spring:
  application:
    name: watermark-worker-service
  datasource:
    url: jdbc:postgresql://${LOCAL_DB_HOST}:${LOCAL_DB_PORT}/watermark_db?user=${LOCAL_DB_USERNAME}&password=${LOCAL_DB_PASSWORD}&sslmode=${LOCAL_DB_SSL_MODE}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  output:
    ansi:
      enabled: ALWAYS

  kafka:
    consumer:
      group-id: watermark-workers
      enable-auto-commit: false
      max-poll-records: 50
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "com.system_share_documents.AppCommonService.event"
        spring.json.value.default.type: "com.system_share_documents.AppCommonService.event.WatermarkJobEvent"

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.system_share_documents: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

watermark:
  stripes: 128
  localRetries: 3

minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}

document-key:
  service-name: document-service
  url: lb://document-service
  create-document-key: /api/documents/key/create

grant-access:
  service-name: auth-access-control-service
  url: lb://auth-access-control-service
  check-grant-access: /api/document-access/check-access
  create-grant-access: /api/document-access/grant

keycloak:
  token-base-url: ${KEYCLOAK_URL}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/token
  client-id: ${KEYCLOAK_TOKEN_CLIENT_ID}
  client-secret: ${KEYCLOAK_TOKEN_CLIENT_SECRET}

vault:
  scheme: http
  host: ${VAULT_HOST}
  port: ${VAULT_PORT}
  token: ${VAULT_TOKEN}
  transit-key: ${VAULT_TRANSIT_KEY}