plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.0'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.system_share_documents'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    // Security cho JWT
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.security:spring-security-oauth2-resource-server:6.2.1'
    implementation 'org.springframework.security:spring-security-oauth2-jose:6.2.1'
    // Actuator cho giám sát
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    // JPA và PostgreSQL cho log
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    runtimeOnly 'org.postgresql:postgresql'
    // Lombok
    implementation 'org.projectlombok:lombok:1.18.34'
    annotationProcessor 'org.projectlombok:lombok:1.18.34'
    // Lombok + MapStruct binding
    annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'
    // MapStruct
    implementation 'org.mapstruct:mapstruct:1.5.5.Final'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'
    //Eureka
    implementation 'org.springframework.cloud:spring-cloud-starter-netflix-eureka-client'
    implementation 'org.springframework.cloud:spring-cloud-starter-loadbalancer'
    // Minio
    implementation 'io.minio:minio:8.5.17'
    // OpenPGP
    implementation 'org.bouncycastle:bcprov-jdk18on:1.78.1'
    implementation 'org.bouncycastle:bcpg-jdk18on:1.78.1'
    // Config Client
    implementation 'org.springframework.cloud:spring-cloud-starter-config'
    implementation('org.springframework.cloud:spring-cloud-starter-bootstrap')
    // spring-dotenv (nạp .env)
    implementation "me.paulschwarz:spring-dotenv:3.0.0"
    // Redis
    implementation 'com.redislabs:jredisearch:2.2.0'
    implementation 'redis.clients:jedis:3.7.1'
    // Elasticsearch
    implementation 'com.google.guava:guava:33.0.0-jre'
    implementation 'org.elasticsearch.client:elasticsearch-rest-high-level-client:7.10.2'
    implementation 'org.elasticsearch:elasticsearch:7.10.2'
    // Testing
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    //Source common
    implementation project(':AppCommonService')
}

dependencyManagement {
    imports {
        mavenBom 'org.springframework.cloud:spring-cloud-dependencies:2023.0.1'
    }
}

tasks.named('test') {
    useJUnitPlatform()
}