server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # Admin audit endpoints - phải đặt trước user-service route để match trước
        - id: audit-log-service-admin
          uri: lb://audit-log-service
          predicates:
            - Path=/admin/audit/**
          filters:
            - PreserveHostHeader
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/auth/**, /api/users/**, /api/keys/**,/api/groups/**, /internal/users/**, /internal/groups/**, /debug/**, /admin/**
          filters:
            - PreserveHostHeader
        - id: document-service
          uri: lb://document-service
          predicates:
            - Path=/api/documents/**
          filters:
            - PreserveHostHeader
        - id: auth-access-control-service
          uri: lb://auth-access-control-service
          predicates:
            - Path=/api/document-access/**
          filters:
            - PreserveHostHeader
        - id: audit-log-service
          uri: lb://audit-log-service
          predicates:
            - Path=/api/audit/**, /internal/audit/**
          filters:
            - PreserveHostHeader
  datasource:
    url: jdbc:postgresql://${LOCAL_DB_HOST}:${LOCAL_DB_PORT}/gateway_db?user=${LOCAL_DB_USERNAME}&password=${LOCAL_DB_PASSWORD}&sslmode=${LOCAL_DB_SSL_MODE}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
